### ISSUE TITLE
Please release a v0.2.2

### ISSUE THREAD

**Issue by jljouannic** [joakim/rollup-plugin-espruino#2]
Would you mind making a new release as the last one is pretty old and does not include some fixed bug (like this one: https://github.com/joakim/rollup-plugin-espruino/commit/3faa8c2faaa7f1b0a53367ba56533ac6d35952e4)?

**Comment by joakim** [comment]
I haven't touched Espruino for a long while, but I'll look into this when I have the time! Thanks for bringing it to my attention.

**Comment by joakim** [comment]
This package is now deprecated. I recommend either using [EspruinoTools' built-in rollup support](https://github.com/espruino/EspruinoTools/pull/80) or [opichals/rollup-plugin-espruino-modules](https://github.com/opichals/rollup-plugin-espruino-modules) directly.
